# Deploy AWS Lambda and Lambda Layers

on:
  push:
    branches:
      - main

name: Auto Deploy to AWS Lambda

jobs:
  deploy:
    name: Auto Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Dependencies
        working-directory: ./functions/fx_auto_trading
        # working-directory: ./functions/deploy_test
        run: |
          npm install serverless -g
          npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build Layer Package
        shell: bash
        run: |
          # docker-compose build layer
          docker build -t layer . 
      
      - name: Deploy to Lambda
        run: |
          # sls plugin install -n serverless-python-requirements
          export SLS_DEBUG=true
          # pip install --upgrade setuptool
          # cd functions/deploy_test && sls deploy
          sls deploy
          
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_LAMBDA_ROLE_ARN: ${{ secrets.AWS_LAMBDA_ROLE_ARN }}
          OANDA_API_ACCOUNT_ID: ${{ secrets.OANDA_API_ACCOUNT_ID }}

      
