version: "3"

services:
  layer:
    # image: python:3.8
    container_name: layer
    build:
      context: .
      dockerfile: ./docker/layers/Dockerfile
    tty: true
    # volumes:
    #   - ./opt/:/srv:rw,delegated
    ports:
      - 3000:3000
    working_dir: /opt
    # env_file: ./.env
    environment:
      TZ: 'Asia/Tokyo'
    # command: python -c "import main; main.lambda_handler({}, None)"
    #   - cp ./requirements.txt ./layers/requirements.txt
      # - pip3 install -r requirements.txt -t ./var/task
  
  # Lambda function (fx_auto_trading)
  fx_auto_trading:
    # image: lambci/lambda:python3.8
    container_name: docker-lambda-local
    tty: true
    build:
      context: .
      dockerfile: ./docker/fx_auto_trading/Dockerfile
    # volumes:
    #   - ./docker/lambda:/var/task:delegated
    #   - ./opt:/opt:delegated
    # volumes:
    #   - ./functions/fx_auto_trading:/var/task:delegated
    #   - ./opt:/opt:delegated,rw
    
    # ports:
    #   - 9001:9001
    working_dir: /var/task
    # env_file: ./.env
    environment:
      # DOCKER_LAMBDA_STAY_OPEN: 1
      # DOCKER_LAMBDA_WATCH: 1
      DOCKER_LAMBDA_DEBUG: 1
      TZ: 'Asia/Tokyo'
    # command: 
    #   - pip install -r requirements.txt
    #   - lambda_function.lambda_handler
    # command: python -c "import lambda_function; lambda_function.lambda_handler({}, None)"
    command: python -c "import lambda_function; lambda_function.lambda_handler({}, None)"
    # command: python3
    # command:
    #   - pip3 install -r requirements.txt -t .
    #   - python lambda_function.py
    
    
  # dynamodb_local
  dynamodb:
    image: amazon/dynamodb-local:1.13.4
    container_name: dynamodb-local-docker-storage
    volumes:
      - "./data:/home/dynamodblocal/data"
    ports:
      - "5984:5984"
    command: "-jar DynamoDBLocal.jar -port 5984 -dbPath ./data -sharedDb"
    
