service: deploy
provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - cloudformation: CreateStack
        # - cloudformation: DescribeStacks
        # - cloudformation: CreateChangeSet
        # - cloudformation: ListStacks
        # - cloudformation: UpdateStack
        # - cloudformation: DescribeChangeSet
        # - cloudformation: ExecuteChangeSet
        # - iam: GetRole
        # - lambda: UpdateFunctionCode
        # - lambda: UpdateFunctionConfig
        # - lambda: GetFunctionConfiguration
        # - lambda: AddPermission
        # - s3: GetObject
      # Resource: "arn:aws:iam::*:role/*"
  role: ${env:AWS_LAMBDA_ROLE_ARN}
  stage: prod

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    pipCmdExtraArgs:
      - setuptools --upgrade

package:
  individually: true

functions:
  deploy_test:
    runtime: python3.8
    name: ${self:service}-${self:provider.stage}--deploy_test
    module: functions/deploy_test
    handler: main.lambda_handler
    environment:
      - DYNAMODB_ENDPOINT: 
        ENV_PARAM_TEST: env_test